### ISSUE TITLE
No node found for selector

### ISSUE THREAD

**Issue by williansmartins** [viniciusgava/itauscraper#15]
Olá Vini, estou vendo aqui que deve ter mudado o HTML do site do Itau.
Eu gostaria de contribuir atualizando o código para corrigir este erro, olha abaixo:

Error: No node found for selector: #varejo > header > div.container > nav > ul > li > div > div > div:nth-child(1) > ul:nth-child(1) > li:nth-child(2) > a
    at assert (/Users/macadmin/dev/projetos/itauscraper/node_modules/puppeteer/lib/helper.js:283:11)
    at DOMWorld.hover (/Users/macadmin/dev/projetos/itauscraper/node_modules/puppeteer/lib/DOMWorld.js:386:5)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async stepExport (/Users/macadmin/dev/projetos/itauscraper/itauscraper.js:45:3)
    at async scraper (/Users/macadmin/dev/projetos/itauscraper/itauscraper.js:171:3)
  -- ASYNC --
    at Frame.<anonymous> (/Users/macadmin/dev/projetos/itauscraper/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.hover (/Users/macadmin/dev/projetos/itauscraper/node_modules/puppeteer/lib/Page.js:1078:29)
    at stepExport (/Users/macadmin/dev/projetos/itauscraper/itauscraper.js:45:14)
    at async scraper (/Users/macadmin/dev/projetos/itauscraper/itauscraper.js:171:3)

**Comment by williansmartins** [comment]
@viniciusgava , estou com dificuldade para fechar o modal que aparece assim que logamos, pode dar um help?

![image](https://user-images.githubusercontent.com/4259203/151167670-5e040469-2467-48f1-a90a-6a47b8bcf68b.png)

Estou tentando fazer um click neste button, mas não vai, não da erro, mas não sai do lugar tambem:

![image](https://user-images.githubusercontent.com/4259203/151167818-e443ca45-5d93-4df1-bfb3-2ab5275c01ff.png)

**Comment by viniciusgava** [comment]
Olá @williansmartins , tudo bom? Atualmente o script da master está quebrado. Eu tenho trabalho algumas horas por dia pra arrumar. Existe algumas coisas não comitadas, porém a versão nessa branch está funcional.
https://github.com/viniciusgava/itauscraper/tree/fixing-checking-account-2022


Sobre esse popup, o código que deveria fechar ela é esse:
https://github.com/viniciusgava/itauscraper/blob/fixing-checking-account-2022/itauscraper.js#L102-L106

**Comment by williansmartins** [comment]
Legal, vou ver esta outra branch, obrigado pela atenção.

**Comment by williansmartins** [comment]
Perfeito, esta branch esta funcional aqui também. Vou fechar a issue.
Muito obrigado.
Se precisar de ajuda e eu conseguir ajudar em algo, só chamar.

**Comment by viniciusgava** [comment]
@williansmartins Publiquei a versão [1.3.0](https://github.com/viniciusgava/itauscraper/releases/tag/1.3.0) e [1.3.1](https://github.com/viniciusgava/itauscraper/releases/tag/1.3.1) que tem todas correções, bibliotecas atualizadas e docker funcional também. A [branch](https://github.com/viniciusgava/itauscraper/pull/16)  foi removida já que já foi mergeada.

**Comment by williansmartins** [comment]
valeu!!!
